### ISSUE TITLE
App.py

### ISSUE THREAD

**Issue by StandartCoder** [Mondmarmelade/Kahboom#2]
if to array

**Comment by Mondmarmelade** [comment]
For a more detailed explanation: The if query is to be replaced by an array with the individual colors.  The "i" variable is then used as the position in the array.  
Code: https://github.com/Mondmarmelade/Kahboom/blob/main/app.py#L36-L43

**Comment by Mondmarmelade** [comment]
Added Changes in e8efc2b137a128ed072b8845311d9380d98d1d2f
