### ISSUE TITLE
"QuizName" misspelled 

### ISSUE THREAD

**Issue by Mondmarmelade** [Mondmarmelade/Kahboom#5]
On the page "https://kahboom.tk/quizName/*", Quiz Name is written "QuizName".

**Comment by StandartCoder** [comment]
That is not abnormal that one writes that in such a way! Since one in the programming area, rather little spaces used writes the letter of the new word capital! And usually leaves the first letter lowercase! Therefore, we will not change this!

Kind Regards
~StandartCoder
